// ============================================================
// SchemeGuide — Mock Data
// ============================================================

const CATEGORIES = [
  { id: 1, name: 'Education', icon: '📚', color: 'blue', count: 24 },
  { id: 2, name: 'Healthcare', icon: '🏥', color: 'teal', count: 18 },
  { id: 3, name: 'Agriculture', icon: '🌾', color: 'green', count: 15 },
  { id: 4, name: 'Employment', icon: '💼', color: 'amber', count: 20 },
  { id: 5, name: 'Housing', icon: '🏠', color: 'navy', count: 12 },
  { id: 6, name: 'Women & Child', icon: '👩‍👧', color: 'pink', count: 16 },
  { id: 7, name: 'Senior Citizens', icon: '👴', color: 'orange', count: 10 },
  { id: 8, name: 'Disability', icon: '♿', color: 'purple', count: 8 },
  { id: 9, name: 'Financial Assistance', icon: '💰', color: 'gold', count: 22 },
];

const DEPARTMENTS = [
  { id: 1, name: 'Ministry of Education', desc: 'Manages educational policies and scholarship programs', contact: 'edu@gov.in', website: 'education.gov.in' },
  { id: 2, name: 'Ministry of Health', desc: 'Oversees healthcare schemes and public health', contact: 'health@gov.in', website: 'mohfw.gov.in' },
  { id: 3, name: 'Ministry of Agriculture', desc: 'Agricultural development and farmer welfare', contact: 'agri@gov.in', website: 'agriculture.gov.in' },
  { id: 4, name: 'Ministry of Labour', desc: 'Employment, labor welfare and skill development', contact: 'labour@gov.in', website: 'labour.gov.in' },
  { id: 5, name: 'Ministry of Housing', desc: 'Housing for all and urban development', contact: 'housing@gov.in', website: 'mohua.gov.in' },
  { id: 6, name: 'Ministry of Women & Child Development', desc: 'Welfare programs for women and children', contact: 'wcd@gov.in', website: 'wcd.nic.in' },
  { id: 7, name: 'Ministry of Social Justice', desc: 'Social empowerment and disability welfare', contact: 'social@gov.in', website: 'socialjustice.gov.in' },
  { id: 8, name: 'Ministry of Finance', desc: 'Financial inclusion and economic assistance', contact: 'finance@gov.in', website: 'finmin.nic.in' },
];

const STATES = ['All States','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'];

const SCHEMES = [
  {
    id: 1,
    name: 'AICTE Pragati Scholarship for Girls',
    shortDesc: 'Financial support for girl students pursuing technical education.',
    description: 'The AICTE Pragati Scholarship provides financial assistance to girl students enrolled in AICTE approved institutions for pursuing technical education (degree and diploma). The scheme aims to advance technical education among girls.',
    category: 'Education',
    department: 'Ministry of Education',
    state: 'All States',
    benefit: '₹50,000 per annum',
    benefitDetail: 'Annual scholarship of ₹50,000 along with contingency allowance.',
    status: 'Active',
    lastUpdated: '2024-03-15',
    views: 4521,
    tags: ['scholarship', 'girls', 'technical education'],
    eligibility: {
      age: { min: 18, max: 30 },
      gender: ['Female'],
      income: { max: 800000 },
      education: ['Diploma', "Bachelor's Degree"],
      occupation: ['Student'],
      community: ['All'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Gender', requirement: 'Female' },
      { label: 'Course', requirement: 'Technical (AICTE approved)' },
      { label: 'Annual Income', requirement: 'Below ₹8,00,000' },
      { label: 'Age', requirement: '18 to 30 years' },
    ],
    documents: ['Aadhaar Card', 'Marksheets (Class 10 & 12)', 'Income Certificate', 'Bank Account Details', 'Admission Letter'],
    applicationProcess: ['Register on National Scholarship Portal', 'Fill application form with accurate details', 'Upload required documents', 'Submit before deadline', 'Track application status online'],
    applicationURL: 'https://scholarships.gov.in',
    popular: true,
    recommended: true,
  },
  {
    id: 2,
    name: 'PM Kisan Samman Nidhi',
    shortDesc: 'Income support of ₹6,000/year to small and marginal farmers.',
    description: 'PM-KISAN is a Central Sector scheme with 100% funding from the Government of India that provides income support to all landholding farmers to supplement their financial needs.',
    category: 'Agriculture',
    department: 'Ministry of Agriculture',
    state: 'All States',
    benefit: '₹6,000 per year',
    benefitDetail: '₹6,000 per year in three installments of ₹2,000 each.',
    status: 'Active',
    lastUpdated: '2024-04-01',
    views: 8920,
    tags: ['farmer', 'income support', 'agriculture'],
    eligibility: {
      age: { min: 18, max: 100 },
      gender: ['Male', 'Female', 'Other'],
      income: { max: 200000 },
      education: ['All'],
      occupation: ['Farmer'],
      community: ['All'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Occupation', requirement: 'Farmer (landholding)' },
      { label: 'Annual Income', requirement: 'Below ₹2,00,000' },
      { label: 'Age', requirement: '18 years and above' },
    ],
    documents: ['Land Records (Khatoni/Patta)', 'Aadhaar Card', 'Bank Account Details', 'Mobile Number linked to Aadhaar'],
    applicationProcess: ['Visit nearest CSC center or official website', 'Fill PM-KISAN registration form', 'Provide land and bank details', 'Verification by local authorities', 'Amount directly credited to bank'],
    applicationURL: 'https://pmkisan.gov.in',
    popular: true,
    recommended: false,
  },
  {
    id: 3,
    name: 'Ayushman Bharat PM-JAY',
    shortDesc: 'Health cover of ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    description: 'Pradhan Mantri Jan Arogya Yojana (PM-JAY) is the world\'s largest health insurance scheme fully financed by the government providing cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    category: 'Healthcare',
    department: 'Ministry of Health',
    state: 'All States',
    benefit: '₹5 Lakh health cover',
    benefitDetail: 'Cashless hospitalization up to ₹5 lakh per family per year.',
    status: 'Active',
    lastUpdated: '2024-02-10',
    views: 12450,
    tags: ['health insurance', 'hospitalization', 'cashless'],
    eligibility: {
      age: { min: 0, max: 100 },
      gender: ['Male', 'Female', 'Other'],
      income: { max: 200000 },
      education: ['All'],
      occupation: ['All'],
      community: ['All'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Income', requirement: 'Below Poverty Line / SECC listed' },
      { label: 'Family', requirement: 'All family members covered' },
    ],
    documents: ['Aadhaar Card', 'Ration Card', 'Income Certificate', 'SECC data verification'],
    applicationProcess: ['Check eligibility on pmjay.gov.in', 'Visit empanelled hospital', 'Show Aadhaar/ration card at hospital help desk', 'Get Ayushman card issued', 'Avail cashless treatment'],
    applicationURL: 'https://pmjay.gov.in',
    popular: true,
    recommended: true,
  },
  {
    id: 4,
    name: 'National Scholarship Portal — Merit-cum-Means',
    shortDesc: 'Merit-based scholarship for minority community students.',
    description: 'Merit-cum-Means Scholarship is available for students belonging to minority communities who are pursuing professional and technical courses at undergraduate and postgraduate levels.',
    category: 'Education',
    department: 'Ministry of Education',
    state: 'All States',
    benefit: '₹20,000 per annum',
    benefitDetail: 'Course fee up to ₹20,000 and maintenance allowance of ₹1,000/month.',
    status: 'Active',
    lastUpdated: '2024-01-20',
    views: 3210,
    tags: ['minority', 'scholarship', 'professional courses'],
    eligibility: {
      age: { min: 16, max: 30 },
      gender: ['Male', 'Female', 'Other'],
      income: { max: 250000 },
      education: ["Bachelor's Degree", "Master's Degree"],
      occupation: ['Student'],
      community: ['Minority'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Community', requirement: 'Minority (Muslim/Sikh/Christian/Buddhist/Parsi/Jain)' },
      { label: 'Annual Income', requirement: 'Below ₹2,50,000' },
      { label: 'Marks', requirement: 'At least 50% in previous exam' },
    ],
    documents: ['Community Certificate', 'Income Certificate', 'Marksheets', 'Institution Verification', 'Bank Account Details'],
    applicationProcess: ['Register on National Scholarship Portal', 'Select Merit-cum-Means scholarship', 'Fill form with academic and income details', 'Upload documents', 'Submit and track'],
    applicationURL: 'https://scholarships.gov.in',
    popular: false,
    recommended: true,
  },
  {
    id: 5,
    name: 'PM Awas Yojana (Urban)',
    shortDesc: 'Affordable housing for urban poor under "Housing for All" mission.',
    description: 'Pradhan Mantri Awas Yojana (Urban) aims to provide housing for all urban poor. The scheme offers interest subsidy on home loans and direct assistance for house construction.',
    category: 'Housing',
    department: 'Ministry of Housing',
    state: 'All States',
    benefit: 'Up to ₹2.67 Lakh subsidy',
    benefitDetail: 'Interest subsidy up to 6.5% on home loans for eligible categories.',
    status: 'Active',
    lastUpdated: '2024-03-28',
    views: 6780,
    tags: ['housing', 'home loan', 'urban'],
    eligibility: {
      age: { min: 18, max: 70 },
      gender: ['Male', 'Female', 'Other'],
      income: { max: 1800000 },
      education: ['All'],
      occupation: ['All'],
      community: ['EWS', 'LIG', 'MIG'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Income Group', requirement: 'EWS / LIG / MIG' },
      { label: 'Home Ownership', requirement: 'Should not own a pucca house' },
      { label: 'Location', requirement: 'Urban area' },
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Property Documents', 'Bank Account Details', 'Caste Certificate (if applicable)'],
    applicationProcess: ['Apply through local municipal body', 'Submit application with documents', 'Verification by officials', 'Sanction of loan with subsidy', 'Construction begins'],
    applicationURL: 'https://pmaymis.gov.in',
    popular: true,
    recommended: false,
  },
  {
    id: 6,
    name: 'Beti Bachao Beti Padhao',
    shortDesc: 'Scheme to promote welfare of girl child and women empowerment.',
    description: 'Beti Bachao Beti Padhao scheme aims to address the declining Child Sex Ratio and related issues of disempowerment of women. It focuses on survival, protection and education of the girl child.',
    category: 'Women & Child',
    department: 'Ministry of Women & Child Development',
    state: 'All States',
    benefit: 'Multiple benefits',
    benefitDetail: 'Educational support, conditional cash transfers, and social welfare programs.',
    status: 'Active',
    lastUpdated: '2024-02-14',
    views: 5430,
    tags: ['girl child', 'education', 'women empowerment'],
    eligibility: {
      age: { min: 0, max: 25 },
      gender: ['Female'],
      income: { max: 500000 },
      education: ['All'],
      occupation: ['All'],
      community: ['All'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Gender', requirement: 'Girl child / Women' },
      { label: 'Age', requirement: 'Up to 25 years' },
    ],
    documents: ['Birth Certificate', 'Aadhaar Card', 'School Enrollment Proof', 'Income Certificate'],
    applicationProcess: ['Visit Anganwadi or District office', 'Fill application form', 'Submit documents', 'Enroll in programme', 'Avail benefits as per scheme component'],
    applicationURL: 'https://wcd.nic.in',
    popular: false,
    recommended: true,
  },
  {
    id: 7,
    name: 'Skill India Mission — PMKVY',
    shortDesc: 'Free skill training and certification for youth to enhance employability.',
    description: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY) is the flagship scheme of Ministry of Skill Development. Objectives of this skill certification scheme is to enable a large number of Indian youth to take up industry-relevant skill training.',
    category: 'Employment',
    department: 'Ministry of Labour',
    state: 'All States',
    benefit: 'Free training + ₹8,000 reward',
    benefitDetail: 'Free skill certification and monetary reward up to ₹8,000 on completion.',
    status: 'Active',
    lastUpdated: '2024-04-05',
    views: 9870,
    tags: ['skill development', 'employment', 'youth', 'training'],
    eligibility: {
      age: { min: 15, max: 45 },
      gender: ['Male', 'Female', 'Other'],
      income: { max: 500000 },
      education: ['Primary', 'Secondary', 'Higher Secondary', 'All'],
      occupation: ['Unemployed', 'Student'],
      community: ['All'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Age', requirement: '15 to 45 years' },
      { label: 'Status', requirement: 'Unemployed / Seeking employment' },
    ],
    documents: ['Aadhaar Card', 'Educational Certificates', 'Bank Account Details', 'Passport Photo'],
    applicationProcess: ['Find nearest PMKVY training center', 'Register online or walk-in', 'Choose skill course', 'Complete training', 'Appear for assessment and get certified'],
    applicationURL: 'https://pmkvyofficial.org',
    popular: true,
    recommended: true,
  },
  {
    id: 8,
    name: 'Senior Citizen Welfare Fund',
    shortDesc: 'Financial assistance and healthcare support for senior citizens above 60.',
    description: 'The Senior Citizen Welfare Fund provides various benefits including financial assistance, healthcare, and social security measures for senior citizens in India.',
    category: 'Senior Citizens',
    department: 'Ministry of Social Justice',
    state: 'All States',
    benefit: 'Multiple benefits',
    benefitDetail: 'Monthly pension, medical aid, and travel concessions.',
    status: 'Active',
    lastUpdated: '2024-01-10',
    views: 2340,
    tags: ['pension', 'senior citizen', 'elderly'],
    eligibility: {
      age: { min: 60, max: 100 },
      gender: ['Male', 'Female', 'Other'],
      income: { max: 200000 },
      education: ['All'],
      occupation: ['Retired', 'Unemployed'],
      community: ['All'],
      state: ['All States'],
      disability: false,
    },
    criteria: [
      { label: 'Age', requirement: '60 years and above' },
      { label: 'Income', requirement: 'Below ₹2,00,000 per annum' },
    ],
    documents: ['Age Proof (Aadhaar/Birth Certificate)', 'Income Certificate', 'Bank Account Details', 'Residence Proof'],
    applicationProcess: ['Visit nearest district social welfare office', 'Submit application form', 'Provide age and income documents', 'Verification process', 'Pension credited monthly'],
    applicationURL: 'https://socialjustice.gov.in',
    popular: false,
    recommended: false,
  },
];

const USERS = [
  { id: 1, name: 'Riya Sharma', email: 'riya@example.com', phone: '9876543210', state: 'Tamil Nadu', status: 'Active', registeredDate: '2024-01-15', applications: 3, age: 22, gender: 'Female', income: 180000, education: "Bachelor's Degree", occupation: 'Student', community: 'General', district: 'Chennai', area: 'Urban', disability: false },
  { id: 2, name: 'Arjun Patel', email: 'arjun@example.com', phone: '9123456789', state: 'Gujarat', status: 'Active', registeredDate: '2024-02-20', applications: 1, age: 35, gender: 'Male', income: 320000, education: 'Secondary', occupation: 'Farmer', community: 'OBC', district: 'Surat', area: 'Rural', disability: false },
  { id: 3, name: 'Priya Nair', email: 'priya@example.com', phone: '9988776655', state: 'Kerala', status: 'Active', registeredDate: '2024-03-10', applications: 2, age: 28, gender: 'Female', income: 250000, education: "Master's Degree", occupation: 'Employed', community: 'General', district: 'Kochi', area: 'Urban', disability: false },
];

const APPLICATIONS = [
  { id: 'APP001', userId: 1, schemeId: 1, schemeName: 'AICTE Pragati Scholarship', appliedDate: '2024-03-20', status: 'Approved', lastUpdated: '2024-04-15', category: 'Education' },
  { id: 'APP002', userId: 1, schemeId: 3, schemeName: 'Ayushman Bharat PM-JAY', appliedDate: '2024-04-02', status: 'Under Review', lastUpdated: '2024-04-20', category: 'Healthcare' },
  { id: 'APP003', userId: 1, schemeId: 7, schemeName: 'Skill India Mission — PMKVY', appliedDate: '2024-04-18', status: 'Submitted', lastUpdated: '2024-04-18', category: 'Employment' },
  { id: 'APP004', userId: 2, schemeId: 2, schemeName: 'PM Kisan Samman Nidhi', appliedDate: '2024-02-28', status: 'Approved', lastUpdated: '2024-03-15', category: 'Agriculture' },
];

const NOTIFICATIONS = [
  { id: 1, type: 'scheme', title: 'New Scheme Available', message: 'A new education scholarship matching your profile has been added.', time: '2 hours ago', read: false, schemeId: 4 },
  { id: 2, type: 'application', title: 'Application Approved', message: 'Your AICTE Pragati Scholarship application has been approved!', time: '1 day ago', read: false, schemeId: 1 },
  { id: 3, type: 'recommendation', title: 'New Recommendations', message: '3 new schemes were found based on your recent activity.', time: '2 days ago', read: true, schemeId: null },
  { id: 4, type: 'update', title: 'Scheme Updated', message: 'PM-JAY eligibility criteria has been updated. Check if you qualify.', time: '3 days ago', read: true, schemeId: 3 },
  { id: 5, type: 'system', title: 'Profile Incomplete', message: 'Complete your profile to get better scheme recommendations.', time: '1 week ago', read: true, schemeId: null },
];

const FEEDBACKS = [
  { id: 1, user: 'Riya Sharma', scheme: 'AICTE Pragati Scholarship', rating: 5, feedback: 'Very helpful! The application process was smooth and I received the scholarship quickly.', date: '2024-04-10' },
  { id: 2, user: 'Arjun Patel', scheme: 'PM Kisan Samman Nidhi', rating: 4, feedback: 'Good scheme but the verification process took a bit long.', date: '2024-03-25' },
  { id: 3, user: 'Priya Nair', scheme: 'Ayushman Bharat PM-JAY', rating: 5, feedback: 'Excellent! Was able to get cashless treatment without any hassle.', date: '2024-04-18' },
];

// App State
const AppState = {
  currentUser: null,
  isAdmin: false,
  currentPage: 'home',
  savedSchemes: [1, 3],
  searchQuery: '',
  filters: {},
  eligibilityData: null,
  eligibilityResult: null,
  selectedScheme: null,
  sidebarOpen: false,
  notificationCount: 2,
};
