// ============================================================
// SchemeGuide — Recommendations Page
// ============================================================

function renderRecommendations(container) {
  const recs = getRecommendations([1, 3, 7]);
  const featured = recs[0];
  const rest = recs.slice(1);

  container.innerHTML = appLayout('recommendations', `
    <div class="page-header">
      <div class="flex justify-between items-start flex-wrap gap-4">
        <div>
          <h1 class="page-title">Recommended for you</h1>
          <p class="page-subtitle">Explore schemes that match your interests and the schemes you've viewed.</p>
        </div>
        <button class="btn btn-outline" onclick="renderRecommendations(document.getElementById('page-content').firstElementChild || document.getElementById('page-content'))">
          ${Icons.refresh} Refresh Recommendations
        </button>
      </div>
    </div>

    <!-- Transparent Explanation -->
    <div class="alert alert-info" style="margin-bottom:var(--space-6)">
      ${Icons.info}
      <div>
        <strong>How recommendations work:</strong> Recommendations are generated by comparing scheme information with your interests and previous activity. A higher match score means the scheme is more similar to what you've explored — it does not mean you are eligible.
      </div>
    </div>

    <!-- Featured Recommendation -->
    ${featured ? `
      <div style="margin-bottom:var(--space-8)">
        <div style="font-size:var(--fs-xs);font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:var(--clr-text-muted);margin-bottom:var(--space-4)">
          Featured • Because you explored Education Scholarships
        </div>
        <div class="card" style="background:linear-gradient(135deg,var(--clr-navy) 0%,#1A4F8A 100%);border:none;position:relative;overflow:hidden">
          <div style="position:absolute;right:-20px;top:-20px;width:150px;height:150px;background:rgba(255,255,255,0.05);border-radius:50%"></div>
          <div class="card-body" style="position:relative;z-index:1">
            <div class="flex justify-between items-start flex-wrap gap-4">
              <div style="max-width:500px">
                <div class="flex gap-2 mb-3 flex-wrap">
                  <span class="badge badge-teal">${featured.category}</span>
                  <span class="badge" style="background:rgba(255,255,255,0.15);color:white">Featured</span>
                </div>
                <h2 style="color:white;margin-bottom:var(--space-3)">${featured.name}</h2>
                <p style="color:rgba(255,255,255,0.75);line-height:1.7;margin-bottom:var(--space-4)">${featured.shortDesc}</p>
                <div class="rec-why" style="background:rgba(255,255,255,0.1);border-left-color:var(--clr-teal);color:rgba(255,255,255,0.8)">
                  ${Icons.spark} <strong>Why recommended:</strong> ${featured.reason}
                </div>
              </div>
              <div style="text-align:center">
                <div style="background:rgba(255,255,255,0.1);border:2px solid rgba(255,255,255,0.2);border-radius:var(--radius-xl);padding:var(--space-6);min-width:140px">
                  <div style="font-size:2.5rem;font-weight:800;color:var(--clr-teal)">${featured.matchScore}%</div>
                  <div style="font-size:var(--fs-xs);color:rgba(255,255,255,0.6)">Match Score</div>
                  <div style="font-size:var(--fs-xs);color:rgba(255,255,255,0.4);margin-top:var(--space-1)">based on your activity</div>
                </div>
                <div style="display:flex;gap:var(--space-3);margin-top:var(--space-4)">
                  <button class="btn btn-teal btn-sm" onclick="navigate('scheme-detail', {scheme:${featured.id}})">View Details</button>
                  <button class="save-btn ${isSaved(featured.id) ? 'saved' : ''}" data-id="${featured.id}"
                    style="background:rgba(255,255,255,0.1);border:1.5px solid rgba(255,255,255,0.2);padding:var(--space-2);border-radius:var(--radius-md);cursor:pointer;color:${isSaved(featured.id) ? 'var(--clr-amber)' : 'rgba(255,255,255,0.6)'}"
                    onclick="toggleSave(${featured.id})">
                    ${isSaved(featured.id) ? Icons.bookmarkFilled : Icons.bookmark}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    ` : ''}

    <!-- Section: Most Relevant -->
    <div style="margin-bottom:var(--space-8)">
      <h3 style="font-size:var(--fs-lg);font-weight:700;color:var(--clr-navy);margin-bottom:var(--space-4)">Most Relevant for You</h3>
      <div class="grid grid-auto" style="gap:var(--space-4)">
        ${rest.slice(0, 3).map(s => recCardHTML(s)).join('')}
      </div>
    </div>

    <!-- Section: Based on Searches -->
    <div style="margin-bottom:var(--space-8)">
      <h3 style="font-size:var(--fs-lg);font-weight:700;color:var(--clr-navy);margin-bottom:var(--space-2)">Based on Your Searches</h3>
      <p style="font-size:var(--fs-sm);color:var(--clr-text-muted);margin-bottom:var(--space-4)">Matching what you've been looking for</p>
      <div class="grid grid-auto" style="gap:var(--space-4)">
        ${rest.slice(3).concat(rest.slice(0, 2)).map(s => recCardHTML(s)).join('')}
      </div>
    </div>

    <!-- Explore Something New -->
    <div>
      <h3 style="font-size:var(--fs-lg);font-weight:700;color:var(--clr-navy);margin-bottom:var(--space-2)">Explore Something New</h3>
      <p style="font-size:var(--fs-sm);color:var(--clr-text-muted);margin-bottom:var(--space-4)">Schemes from categories you haven't explored yet</p>
      <div class="grid grid-auto" style="gap:var(--space-4)">
        ${SCHEMES.filter(s => s.category === 'Agriculture' || s.category === 'Senior Citizens').map(s => recCardHTML({...s, matchScore: Math.floor(55 + Math.random()*20), reason: 'From a category you haven\'t explored yet.'})).join('')}
      </div>
    </div>
  `);
}

function recCardHTML(scheme) {
  const saved = isSaved(scheme.id);
  const catColor = getCategoryColor(scheme.category);
  return `
    <div class="rec-card" onclick="navigate('scheme-detail', {scheme:${scheme.id}})">
      <div class="rec-match-badge">${scheme.matchScore || 80}% Match</div>
      <div class="rec-card-body">
        <div style="padding-top:var(--space-5)">
          <div class="flex gap-2 mb-3">
            <span class="badge badge-${catColor}">${scheme.category}</span>
          </div>
          <div style="font-weight:700;font-size:var(--fs-base);color:var(--clr-navy);margin-bottom:var(--space-2);line-height:1.4;padding-right:var(--space-10)">${scheme.name}</div>
          <div style="font-size:var(--fs-sm);color:var(--clr-text-muted);margin-bottom:var(--space-3)">${scheme.shortDesc}</div>
          <div style="background:var(--clr-primary-light);border-radius:var(--radius-sm);padding:var(--space-2) var(--space-3);font-size:var(--fs-xs);font-weight:600;color:var(--clr-primary);margin-bottom:var(--space-3)">
            ${scheme.benefit}
          </div>
          <div class="rec-why">
            ${Icons.spark} ${scheme.reason || 'Matches your profile and interests.'}
          </div>
          <div class="flex gap-2 mt-4">
            <button class="btn btn-outline btn-sm" onclick="event.stopPropagation(); navigate('scheme-detail', {scheme:${scheme.id}})">View Details</button>
            <button class="save-btn ${saved ? 'saved' : ''}" data-id="${scheme.id}"
              onclick="event.stopPropagation(); toggleSave(${scheme.id})"
              style="padding:var(--space-2) var(--space-3);border-radius:var(--radius-md);border:1.5px solid var(--clr-border);background:transparent;cursor:pointer;font-size:var(--fs-xs);display:flex;align-items:center;gap:4px;color:${saved ? 'var(--clr-amber-dark)' : 'var(--clr-text-muted)'}">
              ${saved ? Icons.bookmarkFilled : Icons.bookmark} ${saved ? 'Saved' : 'Save'}
            </button>
          </div>
        </div>
      </div>
    </div>
  `;
}
